web:
  build: ./web
  links:
    - db
    - mailcatcher
  volumes:
    - ${PROJECT_DIR}src:/var/www/src
    - ${PROJECT_DIR}data/logs/:/var/log/apache2/app/
  ports:
    - ${APP_PORT}:80
  container_name: ${APP_NAME}_web
db:
  image: mysql
  environment:
    MYSQL_USER: ${DB_USER}
    MYSQL_PASS: ${DB_PASS}
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    MYSQL_DATABASE: ${DB_NAME}
  volumes:
    - ${PROJECT_DIR}data/db:/var/lib/mysql
  container_name: ${APP_NAME}_db
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - ${PHPMYADMIN_PORT}:80
  environment:
    MYSQL_USERNAME: ${DB_USER}
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  container_name: ${APP_NAME}_phpmyadmin
mailcatcher:
  image: yappabe/mailcatcher
  ports:
    - ${MAILCATCHER_PORT}:1080
  container_name: ${APP_NAME}_mailcatcher